[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.4"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.7"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"

[prune]
  go-tests = true
  unused-packages = true
